### ISSUE TITLE
Create Content Explorer gui mockup

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-client-js#14]
We need a layout mockup for the new admin page GUI

## Notes:
- Content repository funcions
- Content representations
- UI testing the layout
- Interviews with current users about the admin area
- How to manage SN7 components
- How to manage content types

**Comment by gallayl** [comment]
Issue outdated, admin GUI UX rework has been started in another epic: https://app.zenhub.com/workspaces/sn-team-58d3e1e42f9a23ee7fc47ed7/issues/sensenet/sn-client-core/36
