### ISSUE TITLE
Client side Query API

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-client-js#38]
On client side, we have the fields and the means of querying. So instead of building query strings, we should have an Query API.

ToDo:
- [x] Example
- [x] Tasks

**Comment by gallayl** [comment]
### Syntax example:
```ts
repository.Query('Root/Sites', q => 	// in Root/Sites subtree
	q.TypeIs(ContentTypes.Document)// adds '+TypeIs:Document' and Typescript type cast
	.Equals("Title", "Unicorn")	// adds +Title:Unicorn (TBD: fuzzy/Proximity)
	.And
	.Between("ModificationDate", "2017-01-01T00:00:00", "2017-02-01T00:00:00")
	.Or
	.Query(sub=> sub //Grouping
		.NotEquals("CreatedBy", "admin")
		.And
		.NotEquals("ModifiedBy", "admin")
	)
	.Sort("DisplayName", Sort.Ascending)
	.Top(5)			// adds .TOP:5
	.Skip(10)		// adds .SKIP:10
	.Select("Id", "Path", "Name", "DisplayName")	// OData $select=
	.Expand("Owner")	// OData $expand=
).Exec()	//Fires the request
.subscribe(docs => {
	console.log("Query result:", docs)
})

```

 ### Tasks
 - [ ] Query factory method per Repository instance
 - [ ] Fluent Query API (q => ...)
 - [ ] Comparison
	 - [ ] InTree(Path)
	 - [ ] InFolder(Path)
	 - [ ] Type(ContentTypes.X) // *ToDo: Type intersection?*
	 - [ ] TypeIs (ContentTypes.X) // *ToDo: Type intersection*
	 - [ ] Equals(field, value)
	 - [ ] NotEquals(field, value)
	 - [ ] Between(field, minValue, maxValue) // *ToDo: Inclusive / Exclusive*
	 - [ ] GreatherThan(field, value)// *ToDo: Inclusive / Exclusive*
	 - [ ] LessThan(field, value)// *ToDo: Inclusive / Exclusive*
  - [ ] Operators
	 - [ ] And
	 - [ ] Or
  - [ ] Others
	 - [ ] Not(recursive) 
	 - [ ] Query (recursive)
	 - [ ] Sort
	 - [ ] Top
	 - [ ] Skip
